<?php

namespace Pechynho\PolymorphicDoctrine\Tests\Fixtures;

use Doctrine\Bundle\DoctrineBundle\DoctrineBundle;
use Pechynho\PolymorphicDoctrine\Contract\MetadataProviderInterface;
use Pechynho\PolymorphicDoctrine\Contract\ReferenceClassGeneratorInterface;
use Pechynho\PolymorphicDoctrine\PechynhoPolymorphicDoctrineBundle;
use Symfony\Bundle\FrameworkBundle\FrameworkBundle;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Kernel;

class TestKernel extends Kernel
{
    use MicroKernelTrait;

    public function registerBundles(): iterable
    {
        return [
            new FrameworkBundle(),
            new DoctrineBundle(),
            new PechynhoPolymorphicDoctrineBundle(),
        ];
    }

    protected function configureContainer(ContainerConfigurator $container): void
    {
        $container->extension('framework', [
            'secret' => 'test',
            'test' => true,
            'http_method_override' => false,
        ]);

        $container->extension('doctrine', [
            'dbal' => [
                'driver' => 'pdo_sqlite',
                'url' => 'sqlite:///:memory:',
            ],
            'orm' => [
                'auto_generate_proxy_classes' => true,
                'enable_lazy_ghost_objects' => true,
                'auto_mapping' => false,
                'mappings' => [
                    'TestFixtures' => [
                        'type' => 'attribute',
                        'is_bundle' => false,
                        'dir' => __DIR__.'/Entity',
                        'prefix' => 'Pechynho\PolymorphicDoctrine\Tests\Fixtures\Entity',
                        'alias' => 'TestFixtures',
                    ],
                ],
            ],
        ]);

        // Make services public for tests
        $services = $container->services();
        $services->alias('test.'.MetadataProviderInterface::class, MetadataProviderInterface::class)->public();
        $services->alias('test.'.ReferenceClassGeneratorInterface::class, ReferenceClassGeneratorInterface::class)->public();

        $container->extension('pechynho_polymorphic_doctrine', [
            'references_directory' => '%kernel.cache_dir%/polymorphic-references',
            'references_namespace' => 'Pechynho\PolymorphicDoctrine\Tests\AutogeneratedReference',
            'discover' => [
                'cache_directory' => '%kernel.cache_dir%/polymorphic-discover',
                'directories' => [__DIR__.'/Entity'],
            ],
        ]);
    }

    #[\Override]
    public function getCacheDir(): string
    {
        return \dirname(__DIR__, 2).'/var/test/cache';
    }

    #[\Override]
    public function getLogDir(): string
    {
        return \dirname(__DIR__, 2).'/var/test/log';
    }
}
