<?php

namespace Pechynho\PolymorphicDoctrine;

use Pechynho\PolymorphicDoctrine\Command\ClearCacheCommand;
use Pechynho\PolymorphicDoctrine\Command\GenerateReferenceClassesCommand;
use Pechynho\PolymorphicDoctrine\Contract\ClassNameResolverInterface;
use Pechynho\PolymorphicDoctrine\Contract\MetadataProviderInterface;
use Pechynho\PolymorphicDoctrine\Contract\PolymorphicLocatorInterface;
use Pechynho\PolymorphicDoctrine\Contract\PolymorphicPropertyValueResolverInterface;
use Pechynho\PolymorphicDoctrine\Contract\PolymorphicSearchExprApplierFactoryInterface;
use Pechynho\PolymorphicDoctrine\Contract\PolymorphicSearchExprBuilderFactoryInterface;
use Pechynho\PolymorphicDoctrine\Contract\PolymorphicValueFactoryInterface;
use Pechynho\PolymorphicDoctrine\Contract\ReferenceClassGeneratorInterface;
use Pechynho\PolymorphicDoctrine\DependencyInjection\CompilerPass\PolymorphicCompilerPass;
use Pechynho\PolymorphicDoctrine\Utils\ClassNameResolver;
use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;

use function Symfony\Component\DependencyInjection\Loader\Configurator\param;
use function Symfony\Component\DependencyInjection\Loader\Configurator\service;

/**
 * @phpstan-type BundleConfig = array{references_directory: string, references_namespace: string, discover: array{cache_directory: string, directories: list<string>}}
 */
final class PechynhoPolymorphicDoctrineBundle extends AbstractBundle
{
    private ?\Closure $autoloader = null;

    public function configure(DefinitionConfigurator $definition): void
    {
        $definition->rootNode()
            ->children()
                ->stringNode('references_directory')
                    ->defaultValue('%kernel.cache_dir%/pechynho/polymorphic-doctrine/references')
                ->end()
                ->stringNode('references_namespace')
                    ->defaultValue('Pechynho\PolymorphicDoctrine\AutogeneratedReference')
                ->end()
                ->arrayNode('discover')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->stringNode('cache_directory')
                            ->defaultValue('%kernel.cache_dir%/pechynho/polymorphic-doctrine/discover')
                        ->end()
                        ->arrayNode('directories')
                            ->prototype('scalar')->end()
                            ->defaultValue(['%kernel.project_dir%/src'])
                        ->end()
                    ->end()
                ->end()
            ->end();
    }

    /**
     * @param BundleConfig $config
     */
    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container
            ->parameters()
            ->set('pechynho.polymorphic_doctrine.references_directory', $config['references_directory'])
            ->set('pechynho.polymorphic_doctrine.references_namespace', $config['references_namespace'])
            ->set('pechynho.polymorphic_doctrine.discover.cache_directory', $config['discover']['cache_directory'])
            ->set('pechynho.polymorphic_doctrine.discover.directories', $config['discover']['directories']);

        $services = $container->services();

        // Utils
        $services->set(ClassNameResolver::class)
            ->args([service('doctrine')])
            ->tag('kernel.reset', ['method' => 'reset']);
        $services->alias(ClassNameResolverInterface::class, ClassNameResolver::class);

        // Locator
        $services->set(PolymorphicLocator::class)
            ->args([
                param('pechynho.polymorphic_doctrine.discover.cache_directory'),
                param('pechynho.polymorphic_doctrine.discover.directories'),
                param('kernel.environment'),
                service('filesystem'),
            ]);
        $services->alias(PolymorphicLocatorInterface::class, PolymorphicLocator::class);

        // Metadata
        $services->set(MetadataProvider::class)
            ->args([
                service('cache.app'),
                service(PolymorphicLocatorInterface::class),
                param('pechynho.polymorphic_doctrine.references_directory'),
                param('pechynho.polymorphic_doctrine.references_namespace'),
                param('kernel.environment'),
            ])
            ->tag('kernel.reset', ['method' => 'reset']);
        $services->alias(MetadataProviderInterface::class, MetadataProvider::class);

        // Property value resolver
        $services->set(PolymorphicPropertyValueResolver::class)
            ->args([
                service('doctrine'),
                service(ClassNameResolverInterface::class),
                service('property_accessor'),
            ]);
        $services->alias(PolymorphicPropertyValueResolverInterface::class, PolymorphicPropertyValueResolver::class);

        // Event listener
        $services->set(PolymorphicEventListener::class)
            ->args([
                service(MetadataProviderInterface::class),
                service('property_accessor'),
                service(ClassNameResolverInterface::class),
                service('filesystem'),
                service('doctrine'),
                service(PolymorphicPropertyValueResolverInterface::class),
            ])
            ->tag('doctrine.event_listener', ['event' => 'loadClassMetadata', 'lazy' => true])
            ->tag('doctrine.event_listener', ['event' => 'postLoad', 'lazy' => true])
            ->tag('doctrine.event_listener', ['event' => 'postGenerateSchemaTable', 'lazy' => true]);

        // Value factory (public — used by consumers)
        $services->set(PolymorphicValueFactory::class)
            ->args([
                service(MetadataProviderInterface::class),
                service(PolymorphicPropertyValueResolverInterface::class),
            ])
            ->public();
        $services->alias(PolymorphicValueFactoryInterface::class, PolymorphicValueFactory::class)->public();

        // Search expression builder factory (public — used by consumers)
        $services->set(PolymorphicSearchExprBuilderFactory::class)
            ->args([
                service(MetadataProviderInterface::class),
                service('doctrine.orm.entity_manager'),
                service(ClassNameResolverInterface::class),
                service('property_accessor'),
            ])
            ->public();
        $services->alias(PolymorphicSearchExprBuilderFactoryInterface::class, PolymorphicSearchExprBuilderFactory::class)->public();

        // Search expression applier factory (public — used by consumers)
        $services->set(PolymorphicSearchExprApplierFactory::class)
            ->args([
                service(PolymorphicSearchExprBuilderFactoryInterface::class),
            ])
            ->public();
        $services->alias(PolymorphicSearchExprApplierFactoryInterface::class, PolymorphicSearchExprApplierFactory::class)->public();

        // Reference class generator
        $services->set(ReferenceClassGenerator::class)
            ->args([
                service(MetadataProviderInterface::class),
                param('pechynho.polymorphic_doctrine.references_directory'),
                service('filesystem'),
            ]);
        $services->alias(ReferenceClassGeneratorInterface::class, ReferenceClassGenerator::class);

        // Cache warmer
        $services->set(PolymorphicCacheWarmer::class)
            ->args([
                service(MetadataProviderInterface::class),
                service(ReferenceClassGeneratorInterface::class),
                param('kernel.environment'),
            ])
            ->tag('kernel.cache_warmer');

        // Commands
        $services->set(GenerateReferenceClassesCommand::class)
            ->args([service(ReferenceClassGeneratorInterface::class)])
            ->tag('console.command');

        $services->set(ClearCacheCommand::class)
            ->args([
                service(PolymorphicLocatorInterface::class),
                service(ReferenceClassGeneratorInterface::class),
            ])
            ->tag('console.command');
    }

    public function build(ContainerBuilder $container): void
    {
        $container->addCompilerPass(new PolymorphicCompilerPass());
    }

    public function boot(): void
    {
        $container = $this->container;
        if (!$container instanceof \Symfony\Component\DependencyInjection\ContainerInterface || !$container->hasParameter('pechynho.polymorphic_doctrine.references_directory')) {
            return;
        }
        $referencesDir = $container->getParameter('pechynho.polymorphic_doctrine.references_directory');
        if (!\is_string($referencesDir)) {
            return;
        }
        $fs = new Filesystem();
        if (!$fs->exists($referencesDir)) {
            $fs->mkdir($referencesDir, 0o755);
        }
        $referencesNamespace = $container->getParameter('pechynho.polymorphic_doctrine.references_namespace');
        if (!\is_string($referencesNamespace)) {
            return;
        }
        $this->autoloader = PolymorphicAutoloader::register(
            referencesDir: $referencesDir,
            referencesNamespace: $referencesNamespace,
        );
    }

    public function shutdown(): void
    {
        if ($this->autoloader instanceof \Closure) {
            spl_autoload_unregister($this->autoloader);
            $this->autoloader = null;
        }
    }
}
